services:
  client1:
    image: alpine:3.20
    container_name: nat-client1
    command: ["sh", "-c", "sleep infinity"]
    cap_add:
      - NET_ADMIN
    networks:
      lan:
        ipv4_address: 192.168.10.2

  client2:
    image: alpine:3.20
    container_name: nat-client2
    command: ["sh", "-c", "sleep infinity"]
    cap_add:
      - NET_ADMIN
    networks:
      lan:
        ipv4_address: 192.168.10.3

  router:
    image: alpine:3.20
    container_name: nat-router
    command: ["sh", "-c", "sleep infinity"]
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      lan:
        ipv4_address: 192.168.10.1
      wan:
        ipv4_address: 172.31.0.1

  server:
    image: nginx:alpine
    container_name: nat-server
    networks:
      wan:
        ipv4_address: 172.31.0.2

  wan-client:
    image: alpine:3.20
    container_name: nat-wan-client
    command: ["sh", "-c", "sleep infinity"]
    networks:
      wan:
        ipv4_address: 172.31.0.3

  lan-web:
    image: nginx:alpine
    container_name: nat-lan-web
    cap_add:
      - NET_ADMIN
    networks:
      lan:
        ipv4_address: 192.168.10.4

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.254
  wan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
          gateway: 172.31.0.254
